import type {
  GenerateWorkerPlanDraftInput,
  GenerateWorkerPlanDraftResult,
  ModelProvider,
} from "../model-provider-types";
import { parseJsonModelOutput } from "../json-output-parser";
import type { WorkerPlan } from "../../worker-plan/worker-plan-types";

function extractWorkerPlan(raw: string): { plan: WorkerPlan | null; errors: string[] } {
  const parsed = parseJsonModelOutput(raw);
  if (parsed.success && parsed.parsed) {
    return { plan: parsed.parsed as WorkerPlan, errors: [] };
  }
  return { plan: null, errors: parsed.errors };
}

export class MockModelProvider implements ModelProvider {
  readonly name = "mock";

  async generateWorkerPlanDraft(
    input: GenerateWorkerPlanDraftInput,
  ): Promise<GenerateWorkerPlanDraftResult> {
    const createdAt = new Date().toISOString();
    const targetPath =
      input.allowedFiles[0] ?? "src/generated/worker-plan-draft.ts";

    const plan: WorkerPlan = {
      runId: input.runId,
      summary: `Mock draft for: ${input.taskTitle}`,
      allowedFiles: input.allowedFiles.length > 0
        ? input.allowedFiles.slice(0, input.maxOperations)
        : [targetPath],
      operations: [
        {
          type: "create_file" as const,
          path: input.allowedFiles[0] ?? targetPath,
          content: [
            "// Generated by mock model provider — review before executing",
            `// Task: ${input.taskTitle}`,
            "",
            "export const workerPlanDraftReady = true;",
            "",
          ].join("\n"),
          reason: "Mock provider creates a safe starter file for operator review.",
        },
      ].slice(0, input.maxOperations),
    };

    const rawResponse = JSON.stringify(plan, null, 2);
    const { plan: parsedPlan, errors: parseErrors } = extractWorkerPlan(rawResponse);

    return {
      providerName: this.name,
      modelName: "mock-worker-plan-v1",
      rawResponse,
      parsedPlan,
      parseErrors,
      usage: {
        promptTokens: input.prompt.length,
        completionTokens: rawResponse.length,
        totalTokens: input.prompt.length + rawResponse.length,
        estimatedCostUsd: 0,
      },
      createdAt,
    };
  }
}
